# Generated by Django 2.2.11 on 2020-07-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otpmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpmodel',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
